MongoDBSettings:
  ConnectionString: "mongodb://admin:password@host.docker.internal:27017"
  DatabaseName: "123Completed"
  CollectionName: "events"

RedisSettings:
  ConnectionString: "host.docker.internal:6379"

TimeOutSettings:
  SleepTime: 30000

TimestampSettings:
  Name: "LatestTimestamps"