MongoDBSettings:
  ConnectionString: "mongodb://localhost:27017"
  DatabaseName: "123Completed"
  CollectionName: "events"

RedisSettings:
  ConnectionString: "localhost:6379"

TimeOutSettings:
  SleepTime: 30000

TimestampSettings:
  Name: "LatestTimestamps"